channel:                townssquare
username:               Î»matterbot
iconEmoij:              ghost
mattermostIncoming:     https://.../hooks/...
gitlabApiUrl:           https://my-gitlab-instance.com/
gitlabApiPrivateToken:  xxx-xxxxx
gitlabSystemHookSecret: topSecret